# Generated by Django 2.0.5 on 2018-05-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='applayjob',
            new_name='applyjob',
        ),
    ]
